//
// Created by bigboy on 10/30/20.
//

#ifndef AMONG_US_STE_EDITION_CONSTANTS_H
#define AMONG_US_STE_EDITION_CONSTANTS_H

#define MAX_FAIL_PINGS 1
#define CLIENT_PING_INTERVAL 500
#define MAX_TIME_CLIENT_ACCEPT 1

#endif //AMONG_US_STE_EDITION_CONSTANTS_H
